### ISSUE TITLE
Performance issues with flutter-side timers

### ISSUE THREAD

**Issue by brandonp2412** [brandonp2412/Flexify#2]
After we changed the logic for flutter-side rest timers, while they ran the app started lagging. It was especially noticeable when swiping between tabs. 

Right now I've got it relegated to the notification area, but the Google Play store is refusing my app submissions because it's "misleading" to say the app currently has rest timers. 

@josephnglynn 

I tried reading the performance mode but honestly it just pointed at the StartPlanPage widget and said it was slow, which was not much help. Something about this must be re-rendering a lot of pages at once or something.

https://github.com/brandonp2412/Flexify/commit/02d2fd52eca7c0f40449175136cc294e231d8169

**Comment by josephnglynn** [comment]
Yep, I should have tied the UI update into flutters update cycle instead of forcing the UI to update with `Timer.periodic` at specific time intervals. I'll rectify that in a pull request.

While looking at the profiling I noticed some other issues aswell.
Due to having one state object, and it being listened to at the top of the tree, any change results in the whole app being rebuilt. So I'll split the state out into separate objects.
Also I'm not sure if there's a performance penality, but a lot of async functions are not being awaited and / or some async functions are marked as `void FunctionName async` instead of `Future FunctionName async`

**Comment by brandonp2412** [comment]
The nested navigators make it so you keep the bottom tabs there while you are viewing a plan. It's very nice to have you should try checkout to the version before I added that. The bottom tab gets drawn over and you can't just swipe between your plan and current graphs. I'd say it's worth the 1ms delay

**Comment by josephnglynn** [comment]
I agree, it does look nicer. I tried taking it out and putting it in its own widget so it doesn't rebuild every time with `PlanPage`. Now it seems to have halved to 400 microseconds. Which is less than the `textfields`.

I've had an attempt at fixing the timers [here](https://github.com/brandonp2412/Flexify/pull/3).
Could you let me know if it fixes it?
If not I'll try splitting up the `StartPlanPage` and see if that helps.
