### ISSUE TITLE
I didn't figure it out how to use flexify

### ISSUE THREAD

**Issue by akrram0** [brandonp2412/Flexify#29]
I have been using massive for long time it easy to use and easy to insert your sets and exercices and weights but when I move to flexify I can't figure it out how to use it I love the design it look much much better I hope ican get some help ibeen exercising for 2 weeks since I install this app and each 
time trying to figure it out but I can't so please help

**Comment by akrram0** [comment]
> I have been using massive for long time it easy to use and easy to inserd your sets and exercices etc but when I move to flexify I can't figure it out how to use it and add your sets and exercises I love to design it look much much better I hope ican get some help ibeen exercising for 2 weeks since I install this app and each 
time trying to figure it out but I can't so please help

**Comment by brandonp2412** [comment]
Flexify is built for working out according to a plan. Massive has that option too, but generally has more features and things to choose from. Flexify is not an exact drop-in for Massive, but it is ultimately the project I'm going to be working on.

I'm not making Massive deprecated so don't feel like you have to move across to this project just because it has the latest updates.

**Comment by akrram0** [comment]
> Flexify is built for working out according to a plan. Massive has that option too, but generally has more features and things to choose from. Flexify is not an exact drop-in for Massive, but it is ultimately the project I'm going to be working on.
> 
> I'm not making Massive deprecated so don't feel like you have to move across to this project just because it has the latest updates.

I figure it out it been 2 weeks thank sorry for this stupid question but I have to ask😂
