### ISSUE TITLE
Feature Request: Make entry of body weight exercises with extra weights easier

### ISSUE THREAD

**Issue by motato1** [brandonp2412/Flexify#98]
I believe I've finally found the last exercise tracker I'll ever need. Thank you for this app!
For the last few weeks using it, I've been noticing a usage pattern that is not great in terms of UX.

**Is your feature request related to a problem? Please describe.**
Entering the correct weight for a body weight exercise with extra weights requires manual calculation of the total weight.
E.g. Enter new pull up rep with 5kg extra weight would require me to lookup my weight and add it to 5.

**Describe the solution you'd like**
Tapping the weight button acts as a toggle that adds/doesn't add the body weight to the entered value instead of replacing it.

Any thoughts?

**Comment by brandonp2412** [comment]
The button is a bit confusing because I ended up tracking your current body weight against the set by default. 
So if you enter a pull up with 5kg, the gym set is already saving what your body weight was at that time.

You can see it if you go History -> Pull up -> Body weight field

I think this ticket might be talking about bugs to do with the "Relative strength" feature, which is the main purpose of tracking body weight?

I made this body weight feature a while ago while I was still using Flexify to track my body weight, but I've since started using my other app [FitBook](https://github.com/brandonp2412/FitBook) to do it. 

Making the button add instead of replace the current weight would be easy enough, but i'm not sure it makes sense to have the button at all.

**Comment by motato1** [comment]
The reason why I've opened this issue is, that I'm missing a way to easily track the total amount of weight for my bodyweight exercises.

Since bodyweight fluctuates quite a bit throughout a day/week, even while consuming maintenance calories, I like to choose extra weight based on my body weight, not just what I managed to lift last time.

E.g
Mon: Bodyweight 100kg, extra weight: 10kg
Wed: Bodyweight 98kg, extra weight: 12kg
Fri: Bodyweight 101kg, extra weight 9kg

Before each workout I would step on a scale, then add the extra weight based on that day's bodyweight. That way I have can pick the same resistance every time.

I am not sure if the relative strength feature really helps in my case.

**Comment by brandonp2412** [comment]
> The reason why I've opened this issue is, that I'm missing a way to easily track the total amount of weight for my bodyweight exercises.
> 
> Since bodyweight fluctuates quite a bit throughout a day/week, even while consuming maintenance calories, I like to choose extra weight based on my body weight, not just what I managed to lift last time.
> 
> E.g Mon: Bodyweight 100kg, extra weight: 10kg Wed: Bodyweight 98kg, extra weight: 12kg Fri: Bodyweight 101kg, extra weight 9kg
> 
> Before each workout I would step on a scale, then add the extra weight based on that day's bodyweight. That way I have can pick the same resistance every time.
> 
> I am not sure if the relative strength feature really helps in my case.

Like this?

![pic-window-240815-1325-55](https://github.com/user-attachments/assets/0fa240aa-a4ee-4b9f-bb80-2f596e16507b)
![pic-window-240815-1325-38](https://github.com/user-attachments/assets/dc53cf11-290f-447b-967e-0afb15735a6d)
![pic-window-240815-1325-25](https://github.com/user-attachments/assets/41ba05e5-a3a4-4d3b-b963-fe2782728778)

**Comment by brandonp2412** [comment]
Oh right you mean in the Start Plan page. I would put  your extra weight in the "Weight" field of plans, and then if you wanted to see your past weights then view them in the History. It's already saving your current body weight against each set. If what you want is another field on the plan page to do bodyweight in the same place, I don't think i'll add that since we already have too many fields (plus the height would become different for cardio/strength)

**Comment by motato1** [comment]
Okay, I should work for me.
Thanks for taking the time to respond to my request :smile:
